title: 
email: jnh046522@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: ""
url: https://jwl-97.github.io/
github_username:  jwl-97

# Build settings
remote_theme: chesterhow/tale

# Build settings
markdown:       kramdown
include:
  - _pages

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

permalink:    /:year-:month-:day/:title
paginate:     5

# Assets
sass:
  sass_dir:     _sass
  style:        compressed
  
# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Jiwoo Lee
  url:          https://jwl-97.github.io/
  email:        jnh046522@gmail.com

