title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: chesterhow/tale

# Build settings
markdown:       kramdown
include:
  - _pages

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

permalink:    /:year-:month-:day/:title
paginate:     5

# Assets
sass:
  sass_dir:     _sass
  style:        compressed
  
# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

